### ISSUE TITLE
Fan speed MAX

### ISSUE THREAD

**Issue by dulcetiseduce1** [ladeiko/ASUS-ROG-GL753VE-GC004T-Hackintosh#1]
i tried out your configs i have a gl753ve and i have an issue the fan speed is always at max it seems i have all the files in the right directiories another issue i had was the display calibration was off, blue appeared as purple-ish  im not a huge nerd about hackintosh would you mind to help me out thank you!

**Comment by ladeiko** [comment]
> i tried out your configs i have a gl753ve and i have an issue the fan speed is always at max it seems i have all the files in the right directiories another issue i had was the display calibration was off, blue appeared as purple-ish im not a huge nerd about hackintosh would you mind to help me out thank you!

Hi. It's strange - ACPIPoller.kext should fix fan speed.
Did u rebuild kexts cache with: 

`sudo kextcache -i /`

?

**Comment by dulcetiseduce1** [comment]
think i fixed it might have made a dumb thing 😆 thank you for the suggestion!

**Comment by dulcetiseduce1** [comment]
uhmm tried rebuilding cache and installing the kext but not working yet also the trackpad does it need any software?
